#!/bin/bash
echo "Simple2DGameEngine  / Provides libSimple2DGameEngine.a  / Author : Ammar Qammaz"    

if [ -e libSimple2DGameEngine.a ]
then
  rm libSimple2DGameEngine.a
fi 

  
Optimizations="-O3 -fexpensive-optimizations -s"
CPU="-mfpmath=sse -mtune=core2 -msse -msse2 -msse3"
 
OpenALStuff="`pkg-config --cflags freealut` `pkg-config --libs freealut`"

gcc -fPIC $OpenALStuff  $Optimizations $CPU -c main.c -o main.o 
gcc -fPIC $OpenALStuff $Optimizations $CPU -c sound.c -o sound.o
gcc -fPIC $Optimizations $CPU -c visuals.c -o visuals.o  

FILESTOLINK="main.o sound.o visuals.o"

ar rcs libSimple2DGameEngine.a $FILESTOLINK
rm $FILESTOLINK
 
  

if [ -e libSimple2DGameEngine.a ]
then
  echo "Library Compilation Success.."
else
  echo "Library Compilation Failure.."
fi
 

exit 0
